apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-stg-se-eva
  annotations:
    codefresh.io/environment: staging
    codefresh.io/product: se-vote
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/cf-configs.git
    targetRevision: se
    path: environments/staging/se/cf-vote
  destination:
    namespace: eva-se-stg
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
