apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-prod-wshp-eva
  labels:
    codefresh.io/environment: production
  annotations:
    codefresh.io/product: wshp-result
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/cf-configs.git
    targetRevision: wshp
    path: environments/production/wshp/cf-result
  destination:
    namespace: eva-wshp-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
