apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-stg-main-eva
  annotations:
    codefresh.io/product: main-result
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/cf-configs.git
    targetRevision: main
    path: environments/staging/main/cf-result
  destination:
    namespace: eva-main-stg
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
