apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-prod-eva
  annotations:
    codefresh.io/product: worker
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/configs.git
    targetRevision: HEAD
    path: environments/production/worker
  destination:
    namespace: eva-production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
