apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-env-s-abbr-eva
  labels:
    codefresh.io/environment: env-l
  annotations:
    codefresh.io/product: abbr-worker
spec:
  project: default
  source:
    repoURL: https://github.com/organization/cf-configs.git
    targetRevision: abbr
    path: environments/env-l/abbr/cf-worker
  destination:
    namespace: eva-abbr-env-s
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
