apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-prod-main-eva
  annotations:
    codefresh.io/environment: production
    codefresh.io/product: main-worker
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/cf-configs.git
    targetRevision: main
    path: environments/production/main/cf-worker
  destination:
    namespace: eva-main-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
