apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-prod-se-eva
  annotations:
    codefresh.io/environment: production
    codefresh.io/product: se-worker
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/cf-configs.git
    targetRevision: se
    path: environments/production/se/cf-worker
  destination:
    namespace: eva-se-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
